version: 2
jobs:
  build:
    working_directory: ~/zentra
    docker:
      - image: circleci/python:3.7.1
    steps:
      - checkout
#      - run: sudo chown -R circleci:circleci /usr/local/bin
#      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
#      - restore_cache:
#          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
#      - run:
#          command: |
#            ls
#      - save_cache:
#          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
#          paths:
#            - ".venv"
#            - "/usr/local/bin"
#            - "/usr/local/lib/python3.6/site-packages"
      - run:
          command: |
            python setup.py install
            python setup.py test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
